#!/bin/bash

M_PATH=lib
API_PUBLIC='sed -n  /PUBLIC_API_BEGIN$/,/PUBLIC_API_END$/{/PUBLIC_API_BEGIN$/d;/PUBLIC_API_END$/d;p;} '
files=( "common.h" "activity.h" "user.h" "client.h" "dscrdd.h" "guild.h" "channel.h" "file.h" "message.h" "webhook.h" "con/gateway.h")

{
echo "\
/*
 *     dscrd: Discord C library
 *     Copyright (C) 2018 Jakub Wasylków
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Lesser General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Lesser General Public License for more details.
 *
 *     You should have received a copy of the GNU Lesser General Public License
 *     along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
 "

echo -e "// This file was autogenerated by gen_dscrd_h.sh.\n"

for var in "${files[@]}"
do
    #$API_START "$var" | $API_END 
    echo "// $var"
    $API_PUBLIC "$M_PATH/$var"
done

} > $M_PATH/dscrd.h