#!/bin/bash


M_PATH=lib
API_INTERNAL='sed -n  /@cond[[:space:]]INTERNAL$/,/@endcond$/{/@cond[[:space:]]INTERNAL$/d;/@endcond$/d;p;} '
files=( "common.h" "activity.h" "user.h" "client.h"  "dscrdd.h" "guild.h" \
		"channel.h" "file.h" "message.h" "webhook.h" "json.h" \
		"con/gateway.h" "con/rest.h" "jts/jts_b.h" "jts/jts.h" "jts_types.h")

{

echo "\
/*
 *     dscrd: Discord C library
 *     Copyright (C) 2018 Jakub Wasylków
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Lesser General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Lesser General Public License for more details.
 *
 *     You should have received a copy of the GNU Lesser General Public License
 *     along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
 "

echo "// This file was autogenerated by gen_dscrd_i_h.sh."

for var in "${files[@]}"
do
    #$API_START "$var" | $API_END 
    $API_INTERNAL "$M_PATH/$var"
    # $API_PUBLIC_FILTER "$var" | $API_INTERNAL
done

} > $M_PATH/dscrd_i.h
